# PyEnv makes managing different Python versions a breeze
brew 'pyenv'
brew 'pyenv-virtualenv'

# Fancy zsh prompt thanks to https://github.com/romkatv/powerlevel10k
tap 'romkatv/powerlevel10k'
brew 'powerlevel10k'

# Tunes!
cask 'spotify'

# Markdown notes
cask 'obsidian'

# Shows the next meeting in the menu bar
cask "meetingbar"

# Your personal MacOS butler (mainly for the clipboard history feature)
cask "alfred"

# Google Cloud SDK
cask 'google-cloud-sdk'
