# PyEnv makes managing different Python versions a breeze
brew 'pyenv'

# Fancy zsh prompt thanks to https://github.com/romkatv/powerlevel10k
tap 'romkatv/powerlevel10k'
brew 'powerlevel10k'

# Tunes!
cask 'spotify'